urls.py
from django.conf.urls import url, include
from . import views

app_name = 'Wettbewerbe'

# Hilfspatterns gruppiert
wettbewerbe_urls = [
    url(r'^(?P<slug_prefix>[\w-]+)/(?P<jahrgang>[0-9]+)/(?P<slug>[\w-]+)/$',
        views.EinWettbewerbKonkret.as_view(),
        name='ein_wettbewerb_konkret',
    ),
    url(r'^(?P<slug_prefix>[\w-]+)/(?P<slug>[\w-]+)/$',
        views.EinWettbewerb.as_view(),
        name='ein_wettbewerb_generisch',
    ),
    url(r'^(?P<slug_prefix>[\w-]+)/(?P<jahrgang>[0-9]+)/(?P<slug>[\w-]+)/mich_eintragen/$',
        views.EintragenInWettbewerb.as_view(),
        name='mich_eintragen_wettbewerb',
    ),
]

# Die unmittelbar genutzten url-patterns
urlpatterns = [
    # Übersichtsseiten:
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^listen/$', views.ListenView.as_view(), name='listen'),
    url(r'^wettbewerbe/$',
        views.ListeWettbewerbe.as_view(),
        name='liste_wettbewerbe',
    ),
    url(r'^veranstaltungen/$',
        views.ListeVeranstaltungen.as_view(),
        name='liste_veranstaltungen',
    ),
    url(r'^personen/$',
        views.ListePersonen.as_view(),
        name='liste_personen',
    ),
    # Detailseiten:
    url(r'^wettbewerb/', include(wettbewerbe_urls)),
    url(r'^veranstaltung/(?P<slug>[\w-]+)/$',
        views.EineVeranstaltung.as_view(),
        name='eine_veranstaltung',
    ),
    url(r'^person/(?P<pk>[\w-]+)/$',
        views.EinePerson.as_view(),
        name='eine_person',
    ),
    # sonstige Formulare:
    url(r'^veranstaltung/(?P<slug>[\w-]+)/mich_eintragen/$',
        views.EintragenInVeranstaltung.as_view(),
        name='mich_eintragen_veranstaltung',
    ),
    # Detailseite Tag: GANZ UNTEN
    url(r'^(?P<slug>[\w-]+)/$',
        views.EinTag.as_view(),
        name='ein_tag',
    ),
]

templates/Wettbewerbe/ein_tag.html
{% extends "base.html" %}
{% load seitentags %}

{% block content %}
  <h2>{% listeneintrag tag request %} ({{ tag.art }})</h2>
  <ul>
    {% for wettbewerbk in wettbewerbe %}
    <li>{% listeneintrag wettbewerbk request %}</li>
    {% endfor %}
  </ul>
  <ul>
    {% for veranstaltung in veranstaltungen %}
    <li>{% listeneintrag veranstaltung request %}</li>
    {% endfor %}
  </ul>
  {% if tag.kommentarliste %}{% include 'Kommentare/kommentarliste.html' with liste=tag.kommentarliste %}{% endif %}
{% endblock %}

templates/Wettbewerbe/ein_wettbewerb.html
{% extends "base.html" %}
{% load seitentags %}

{% block content %}
  <h2>Wettbewerb {% listeneintrag wettbewerb request %}</h2>
  <p>{{ wettbewerb.description }}</p>
  <p>Es {% null_ein_viele wettbewerb.erfolge.count "ist kein Erfolg" "ist nur ein Erfolg" "sind {} Erfolge" %} bei diesem Wettbewerb erzielt worden:</p>
  <ul>
    {% for e in wettbewerb.erfolge.all %}
      <li>
        {% if e.person %}
          {% listeneintrag e.person request %}
        {% else %}
          {{ e.nur_name }}
        {% endif %}
         - {{ e.art }}
        {% listeneintrag e request True %}
      </li>
    {% endfor %}
    {% if not request.user.person in wettbewerb.personen.all %}
      <li><a style="color: gray;" href="mich_eintragen/">[meinen Erfolg eintragen]</a></li>
    {% endif %}
  </ul>

  {# Links zur Veranstaltung und anderen Wettbewerben der Veranstaltung #}
  {% if wettbewerb.veranstaltung %}
  Der Wettbewerb hat im Rahmen der Veranstaltung {% listeneintrag wettbewerb.veranstaltung request %} stattgefunden.
    {% ifnotequal wettbewerb.veranstaltung.wettbewerbe.count 1 %}
    <p>Weitere Wettbewerbe auf dieser Veranstaltung:</p>
    <ul>
      {% for w in wettbewerb.veranstaltung.wettbewerbe.all %}
        {% ifnotequal w wettbewerb %}
          <li>{% listeneintrag w request %}</li>
        {% endifnotequal %}
      {% endfor %}
    </ul>
    {% endifnotequal %}
  {% endif %}

  {# Link zur nächsten/vorherigen Runde #}
  {% if fortsetzung %}
    <p>Zur nächsten Runde: {% listeneintrag fortsetzung request %}</p>
  {% endif %}
  {% if vorherige %}
    zu Wettbewerben der vorherigen Runde:
    {% for w in vorherige %}
      <ul>
        <li>{% listeneintrag w request %}</li>
      </ul>
    {% endfor %}
  {% endif %}
  {% if nachbarn %}
    <p>Gleichzeitig finden andere Wettbewerbe zu dieser Wettbewerbsrunde statt:</p>
    <ul>
      {% for w in nachbarn %}
        <li>{% listeneintrag w request %}</li>
      {% endfor %}
    </ul>
  {% endif %}
  {% if wettbewerb.kommentarliste %}{% include 'Kommentare/kommentarliste.html' with liste=wettbewerb.kommentarliste %}{% endif %}
{% endblock %}

templates/Wettbewerbe/eine_person.html
{% extends "base.html" %}
{% load seitentags %}

{% block content %}
  <h2>Person {% listeneintrag person request %}</h2>
  <p>Es sind folgende {{ person.teilnahmen.count }} Teilnahmen an Veranstaltungen bekannt:</p>
  <ul>
    {% for t in person.teilnahmen.all %}
      <li>
        {% listeneintrag t.veranstaltung request %} - {{ t.art }}
        {% listeneintrag t request True %}
      </li>
    {% endfor %}
  </ul>
  <p>Es sind folgende {{ person.erfolge.count }} Erfolge bei Wettbewerben bekannt:</p>
  <ul>
    {% for e in person.erfolge.all %}
      <li>
        {% listeneintrag e.wettbewerb request %} - {{ e.art }}
        {% listeneintrag e request True %}
      </li>
    {% endfor %}
  </ul>
{% endblock %}

templates/Wettbewerbe/eine_veranstaltung.html
{% extends "base.html" %}
{% load seitentags %}

{% block content %}
<h2>{% listeneintrag veranstaltung request %}</h2>
  <p>{{ veranstaltung.datum_anfang }} - {{ veranstaltung.datum_ende }} </p>
  <p>{{ veranstaltung.description }}</p>
  <p>Es {% null_ein_viele veranstaltung.teilnahmen.count %} an der Veranstaltung bekannt:</p>
  <ul>
    {% for t in veranstaltung.teilnahmen.all %}
      <li>
        {% if t.person %}
          {% listeneintrag t.person request %}
        {% else %}
          {{ t.nur_name }}
        {% endif %}
         - {{ t.art }}
         {% listeneintrag t request True %}
      </li>
    {% endfor %}
    {% if not request.user.person in veranstaltung.personen.all %}
      <li><a style="color: gray;" href="mich_eintragen/">[meine Teilnahme eintragen]</a></li>
    {% endif %}
  </ul>
  {% if veranstaltung.wettbewerbe.all %}
  <p>Es sind folgende Wettbewerbe bei dieser Veranstaltung ausgetragen worden</p>
  <ul>
    {% for w in veranstaltung.wettbewerbe.all %}
      <li>
      {% listeneintrag w request %}
      {% if w.erfolge.all %}
        <br />Folgende Erfolge wurden dabei erreicht
        <ul>
          {% for e in w.erfolge.all %}
            <li>
              {% if e.person %}
                {% listeneintrag e.person request %}
              {% else %}
                {{ e.nur_name }}
              {% endif %}
               - {{ e.art }}{% listeneintrag e request True %}
            </li>
          {% endfor %}
        </ul>
      {% endif %}
      </li>
    {% endfor %}
  </ul>
  {% endif %}
  {% if veranstaltung.kommentarliste %}{% include 'Kommentare/kommentarliste.html' with liste=veranstaltung.kommentarliste %}{% endif %}
{% endblock %}

templates/Wettbewerbe/formular_teilnahme_micheintragen.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<p> {{ form.instance.person.name }}, Sie nehmen an {{ form.instance.veranstaltung }}{{ form.instance.wettbewerb.title }} teil? </br>Bitte wählen Sie die Art der Teilnahme!:</p>
  <form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Teilnahme eintragen!">
  </form>
{% endblock content %}

templates/Wettbewerbe/index.html
{% extends "base.html" %}
{% load seitentags %}

{% block zusatz_css %}
<style>
  article {
    display: flex;
    display: -webkit-flex;
    -webkit-flex-flow: row wrap;
    flex-flow: row wrap;
  }
  fieldset.kategorie {
    display: flex;
    display: -webkit-flex;
    border-radius: 6pt;
    margin: 7px 9px 4px 4px;
    -webkit-flex-flow: column wrap;
    flex-flow: column wrap;
    flex: 1 36ex;
  }
</style>
{% endblock %}

{% block content %}
  {% for name, liste in kategorien %}
    <fieldset class="kategorie">
      <legend>{{ name }}</legend>
        {% for objekt in liste %}
        <div>{% listeneintrag objekt request %}<div>
        {% endfor %}
    </fieldset>
  {% endfor %}
{% endblock %}

templates/Wettbewerbe/liste_personen.html
{% extends "base.html" %}

{% block content %}
  {% include 'Grundgeruest/separator.html' with text="Liste der bisher eingetragenen Personen" %}
  <ul>
    {% for person in personen %}
    <li><a href="{% url 'Wettbewerbe:eine_person' pk=person.pk %}">{{ person.name }}: {{ person.teilnahmen.count }} Teilnahmen und {{ person.erfolge.count }} Erfolge</a></li>
    {% endfor %}
  </ul>
{% endblock %}

templates/Wettbewerbe/liste_veranstaltungen.html
{% extends "base.html" %}

{% block content %}
  {% include 'Grundgeruest/separator.html' with text="Liste der bisher eingetragenen Veranstaltungen" %}
  <ul>
    {% for veranstaltung in veranstaltungen %}
    <li><a href={{ veranstaltung.get_absolute_url }}>{{ veranstaltung.name }}: {{ veranstaltung.teilnahmen.count }} Teilnahmen</a></li>
    {% endfor %}
  </ul>
{% endblock %}

templates/Wettbewerbe/liste_wettbewerbe.html
{% extends "base.html" %}

{% block content %}
  {% include 'Grundgeruest/separator.html' with text="Liste der bisher eingetragenen Wettbewerbe" %}
  <ul>
    {% for wettbewerb in wettbewerbe %}
    <li><a href={{ wettbewerb.get_absolute_url }}>{{ wettbewerb.name }}: {{ wettbewerb.erfolge.count }} Einträge</a></li>
    {% endfor %}
  </ul>
{% endblock %}

templates/Wettbewerbe/listen.html
{% extends "base.html" %}
{% load seitentags %}

{% block content %}
  <h1> Übersicht diverser Listen von Objekten </h1>
  {% for name, liste in listen.items %}
  <p>Liste der {{ name.title }}:</p>
    <ul>
    {% for item in liste %}
      <li>
        {% listeneintrag item request %}
      </li>
    {% endfor %}
    </ul>
  {% endfor %}
  <p>
    tertiam non olet: {% lorem 46 w %}!
    <br> {% lorem 81 w random %}.
  </p>

{% endblock %}

templates/Wettbewerbe/tag_detail.html
{% extends "base.html" %}

{% block content %}
  <h2>{{ tag.name }} ({{ tag.art }})</h2>
  <ul>
    {% for wettbewerbk in liste %}
    	<li><a href={{ wettbewerbk.get_absolute_url }}>{{ wettbewerbk.name }}</a></li>
    {% endfor %}
  </ul>
  {% if tag.rangliste_ausgeben %}
  Folgende Personen sind in diesem {{ tag.art }} erfolgreich gewesen
  <ul>
  	{% for personk, punkte in tag.rangliste_ausgeben %}
  		<li><a href={{ personk.get_absolute_url }}>{{ personk.name }}</a></li> {{ punkte }}
  	{% endfor %}
  </ul>
  {% endif %}
{% endblock %}